### ISSUE TITLE
Recruiter Interview: Sara Gorjão

### ISSUE THREAD

**Issue by donbonifacio** [donbonifacio/blog#24]

**Comment by donbonifacio** [comment]
Hey Sara, can you talk a bit about KWAN and the work you do?

**Comment by saragorjao** [comment]
Hi Pedro ;)
KWAN is a company focused on professional development. Our moto is Love, Respect, Community & the Dollars too. 
We help guide the IT community in finding their next career step. 
If you want to know more please go to http://rupeal.com/en/what or simply read this blog post http://www.kwan.pt/pt/blog/thekwanawakens (I'm sorry it is in Portuguese, and we are working on that). 
Well, regarding the work I do... I'm not the best talking about myself.
I'm afraid I cannot put it into words that easy. Maybe you could help me with that xD

**Comment by donbonifacio** [comment]
Ok, let's go straight to the point then. I want to find great talent to join my team. What things do I need to consider and what strategies can I use to find them?

**Comment by saragorjao** [comment]
Ok. 
First of all, you need to be aware of the culture, the mission and the vision of your company. What you value the most in a person to be part of your team? There are things that you know and feel that make you lean towards a person and not another. 
After that, you should have a draft in your mind of the "job description". What are the "must have's" and what are the "improve upon potential" sides of that job description? 
In terms of strategy, I've been working in this business for 5 years and I have a great asset that helps me a lot in terms of recruitment: my awesome memory :) 
I remember almost everyone that I interviewed in this last 5 years. If I liked you, I'll most likely remember you and will have "an eye on you". 
So my network is pretty good. We have a brand that helps us, we organize tech events and I like to think that we provide a good candidate experience. 
Transparency and feedback are the key to a good recruitment process.

**Comment by donbonifacio** [comment]
Why is the job description so important? What do candidates usually want to see there and how can I make a killer job description?

**Comment by saragorjao** [comment]
Ok. 
The job description is important so you can have in mind the candidate that you are looking for. You don't have to have it written down (in your case, you had no job description and you recruited an entire team). 
Besides that, if you have it written down and you can advertise it, you can create brand awareness and it makes it clear for the candidate the culture of the company that he is applying to. 

Candidates want to see: Who you are (usually not a copy paste from your website); What mission do you have; What will they do in that position; What can they expect from you; What will be expected from them; What stack do you use; Career progression possibilities; Perks; What makes you "you" (something unique about your company). A "Killer Job description" is something clear straight to the point, but out of the box at the same time. 

The job description is important indeed, but is not the most important thing. Networking, good candidate experience and having people saying that they loved working with you is the best thing you can have in this industry.

**Comment by donbonifacio** [comment]
So with a good job description and strategies to find talent, we may have a pipeline of people interested in working with us, and we'll have an interview. How should we prepare this meeting from the point of view of someone that wants to convince the candidate to work for us? What kind of etiquette should we follow? How do we make sure that even if we're not a match, the candidate will be a positive reference?

**Comment by saragorjao** [comment]
OK, answering your questions:
"How should we prepare this meeting from the point of view of someone that wants to convince the candidate to work for us?"
First of all, you cannot have in mind the thought "convincing the candidate to work for us". If you feel the company spirit, if you breathe it, mean it and represent it well, you won't have to convince anyone, You just ARE. You should definitely present the company and the challenge that you have in mind for the person, your core values. And the answer to your other question comes along. 
"What kind of etiquette should we follow?" 
What I usually do is asking the candidate if he knows anything about us, or how did he came across us. After that, I will explain what we do, our core values, our mission. I will tell him a little bit about myself as well, why am I committed to this company and why is it different (practice what we preach kind of thing). I will then ask him to tell me a little bit about him, his motivations, background and why he is looking for a change, what he values most? Then I move to more technical questions, and we end with career aspirations and more soft skills related questions.   
"How do we make sure that even if we're not a match, the candidate will be a positive reference?"
You should think about the candidate as if you were thinking about yourself. Give them UAU moments, give them detailed feedback, keep them in the loop, be kind, add value. :)

**Comment by donbonifacio** [comment]
After the interview we might be interested in making an offer, assuming that the candidate liked us and is aligned with us. What considerations do we need to have to make a killer offer?

**Comment by donbonifacio** [comment]
And when we have two candidates that are equally good, but we can only hire one? What can we do to make a confident choice?

**Comment by donbonifacio** [comment]
And when we interview someone that is not a fit, be it a cultural fit or a technical fit. How to give feedback in a constructive way? Can we make this a positive when saying no?

**Comment by saragorjao** [comment]
Hum.. You should always be kind when giving feedback. 
You should never say "no to the person", which means that when you are giving feedback you should focus the "negative" aspect on behavioral or technical stuff, on facts, and not personal stuff. The positive should be based on personal aspects and things the person did right and should continue to improve upon. 
You should be direct and transparent and the feedback should be focused on "What could you improve". 
Imagine this situation:
_Pedro, I think that you are an awesome leader, your team trusts you and follows your judgment. In this particular situation, I think you haven't considered the Designers point of view, which is so unlikely for someone with an awesome skillset like you have. What might have happened this time? I trust that you are an empathic person and I trust you will think about this next time an event like this occurs._  
Regarding feedback to candidates during the recruitment process, I always say "take it with a pinch of salt, the feedback is meant for you to improve". The candidates always value straightforward feedback, based on facts and areas of improvement. End the feedback on a positive but honest note. 
I would like to receive this kind of feedback, and that's how we do it internally :)

**Comment by donbonifacio** [comment]
That is great advice. Thanks for taking the time to answer my questions, it helped me a lot. Just before we finish, is there someone you'd like to suggest for me to interview next? Someone that could teach me things and help me be better as an engineering manager?

**Comment by saragorjao** [comment]
Thank you for inviting me, it was great :D

I would like to recommend Phil Bannon - Engineering Manager of Hostelworld Portugal. 
It has been a pleasure working with him. Phil is the epitome of transparency, focus on human capital, he is overall an awesome professional. Last year he had the challenge of opening the HW office in Porto and I think sharing his experience and its challenges could of great value. 

Pedro, keep on rocking! You are an inspiration!
